"""add_users_and_shops_tables

Revision ID: 156bb55c528c
Revises: 
Create Date: 2025-09-08 19:31:39.039795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '156bb55c528c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('shop_id', sa.BigInteger(), nullable=False, comment='店铺ID'),
    sa.Column('sku', sa.Text(), nullable=False, comment='商品SKU'),
    sa.Column('qty_available', sa.Integer(), nullable=False, comment='可售库存数量'),
    sa.Column('threshold', sa.Integer(), nullable=False, comment='安全库存阈值'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'sku', name='uq_inventories_shop_sku')
    )
    op.create_index('ix_inventories_shop', 'inventories', ['shop_id'], unique=False)
    op.create_index('ix_inventories_sku', 'inventories', ['sku'], unique=False)
    op.create_index('ix_inventories_threshold', 'inventories', ['shop_id', 'threshold', 'qty_available'], unique=False)
    op.create_index('ix_inventories_updated', 'inventories', ['updated_at'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('shop_id', sa.BigInteger(), nullable=False, comment='店铺ID'),
    sa.Column('sku', sa.Text(), nullable=False, comment='商品SKU'),
    sa.Column('price_rub', sa.NUMERIC(precision=18, scale=4), nullable=False, comment='当前价格（卢布）'),
    sa.Column('price_old_rub', sa.NUMERIC(precision=18, scale=4), nullable=True, comment='划线价（卢布）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'sku', name='uq_listings_shop_sku')
    )
    op.create_index('ix_listings_price', 'listings', ['price_rub'], unique=False)
    op.create_index('ix_listings_shop', 'listings', ['shop_id'], unique=False)
    op.create_index('ix_listings_sku', 'listings', ['sku'], unique=False)
    op.create_index('ix_listings_updated', 'listings', ['updated_at'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False, comment='平台标识，固定为 ozon'),
    sa.Column('shop_id', sa.BigInteger(), nullable=False, comment='店铺ID'),
    sa.Column('external_id', sa.Text(), nullable=False, comment='Ozon order_id'),
    sa.Column('external_no', sa.Text(), nullable=False, comment='posting_number 买家可见编号'),
    sa.Column('status', sa.Text(), nullable=False, comment='本地订单状态'),
    sa.Column('external_status', sa.Text(), nullable=False, comment='Ozon 原始状态'),
    sa.Column('is_cod', sa.Boolean(), nullable=False, comment='是否货到付款'),
    sa.Column('payment_method', sa.Text(), nullable=False, comment='支付方式'),
    sa.Column('buyer_name', sa.Text(), nullable=False, comment='买家姓名'),
    sa.Column('buyer_phone_raw', sa.Text(), nullable=True, comment='买家电话原始格式'),
    sa.Column('buyer_phone_e164', sa.Text(), nullable=True, comment='买家电话 E.164 格式'),
    sa.Column('buyer_email', sa.Text(), nullable=True, comment='买家邮箱'),
    sa.Column('address_country', sa.Text(), nullable=False, comment='国家'),
    sa.Column('address_region', sa.Text(), nullable=False, comment='地区/州'),
    sa.Column('address_city', sa.Text(), nullable=False, comment='城市'),
    sa.Column('address_street', sa.Text(), nullable=False, comment='街道地址'),
    sa.Column('address_postcode', sa.Text(), nullable=False, comment='6位邮编'),
    sa.Column('platform_created_ts', sa.DateTime(timezone=True), nullable=False, comment='平台订单创建时间'),
    sa.Column('platform_updated_ts', sa.DateTime(timezone=True), nullable=False, comment='平台订单更新时间'),
    sa.Column('fx_rate', sa.NUMERIC(precision=18, scale=6), nullable=False, comment='CNY→RUB 汇率快照'),
    sa.Column('currency', sa.Text(), nullable=False, comment='币种'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录更新时间'),
    sa.Column('idempotency_key', sa.Text(), nullable=False, comment='幂等键'),
    sa.CheckConstraint("address_country = 'RU'", name='ck_orders_address_country'),
    sa.CheckConstraint("buyer_phone_e164 IS NULL OR buyer_phone_e164 ~ '^\\+[1-9]\\d{6,14}$'", name='ck_orders_phone_e164_format'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_orders_idempotency_key'),
    sa.UniqueConstraint('platform', 'shop_id', 'external_id', name='uq_orders_platform_shop_external')
    )
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_index('ix_orders_external_no', 'orders', ['external_no'], unique=False)
    op.create_index('ix_orders_shop_updated', 'orders', ['shop_id', 'platform_updated_ts'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False, comment='平台标识'),
    sa.Column('shop_id', sa.BigInteger(), nullable=False, comment='店铺ID'),
    sa.Column('order_external_id', sa.Text(), nullable=False, comment='关联订单外部ID'),
    sa.Column('amount_rub', sa.NUMERIC(precision=18, scale=4), nullable=False, comment='退款金额（卢布）'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='退款创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('returns',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False, comment='平台标识'),
    sa.Column('shop_id', sa.BigInteger(), nullable=False, comment='店铺ID'),
    sa.Column('external_id', sa.Text(), nullable=False, comment='平台退货ID'),
    sa.Column('order_external_id', sa.Text(), nullable=False, comment='关联订单外部ID'),
    sa.Column('reason_code', sa.Text(), nullable=False, comment='退货原因代码'),
    sa.Column('status', sa.Text(), nullable=False, comment='退货状态'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='退货创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='退货更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False, comment='关联订单ID'),
    sa.Column('sku', sa.Text(), nullable=False, comment='商品SKU'),
    sa.Column('offer_id', sa.Text(), nullable=True, comment='Ozon offer_id'),
    sa.Column('qty', sa.Integer(), nullable=False, comment='数量'),
    sa.Column('price_rub', sa.NUMERIC(precision=18, scale=4), nullable=False, comment='单价（卢布）'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_items_order', 'order_items', ['order_id'], unique=False)
    op.create_index('ix_order_items_sku', 'order_items', ['sku'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False, comment='关联订单ID'),
    sa.Column('carrier_code', sa.Text(), nullable=False, comment='承运商代码'),
    sa.Column('tracking_no', sa.Text(), nullable=False, comment='运单号'),
    sa.Column('pushed', sa.Boolean(), nullable=False, comment='是否已回传到平台'),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=True, comment='回传时间'),
    sa.Column('push_receipt', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='平台回传回执'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracking_no', name='uq_shipments_tracking')
    )
    op.create_index('ix_shipments_carrier', 'shipments', ['carrier_code'], unique=False)
    op.create_index('ix_shipments_order', 'shipments', ['order_id'], unique=False)
    op.create_index('ix_shipments_pushed', 'shipments', ['pushed', 'created_at'], unique=False)
    op.create_table('packages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('shipment_id', sa.BigInteger(), nullable=False, comment='关联发运ID'),
    sa.Column('weight_kg', sa.NUMERIC(precision=10, scale=3), nullable=True, comment='重量（公斤）'),
    sa.Column('dim_l_cm', sa.NUMERIC(precision=10, scale=1), nullable=True, comment='长度（厘米）'),
    sa.Column('dim_w_cm', sa.NUMERIC(precision=10, scale=1), nullable=True, comment='宽度（厘米）'),
    sa.Column('dim_h_cm', sa.NUMERIC(precision=10, scale=1), nullable=True, comment='高度（厘米）'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_packages_shipment', 'packages', ['shipment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_packages_shipment', table_name='packages')
    op.drop_table('packages')
    op.drop_index('ix_shipments_pushed', table_name='shipments')
    op.drop_index('ix_shipments_order', table_name='shipments')
    op.drop_index('ix_shipments_carrier', table_name='shipments')
    op.drop_table('shipments')
    op.drop_index('ix_order_items_sku', table_name='order_items')
    op.drop_index('ix_order_items_order', table_name='order_items')
    op.drop_table('order_items')
    op.drop_table('returns')
    op.drop_table('refunds')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_orders_shop_updated', table_name='orders')
    op.drop_index('ix_orders_external_no', table_name='orders')
    op.drop_index('ix_orders_created_at', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_listings_updated', table_name='listings')
    op.drop_index('ix_listings_sku', table_name='listings')
    op.drop_index('ix_listings_shop', table_name='listings')
    op.drop_index('ix_listings_price', table_name='listings')
    op.drop_table('listings')
    op.drop_index('ix_inventories_updated', table_name='inventories')
    op.drop_index('ix_inventories_threshold', table_name='inventories')
    op.drop_index('ix_inventories_sku', table_name='inventories')
    op.drop_index('ix_inventories_shop', table_name='inventories')
    op.drop_table('inventories')
    # ### end Alembic commands ###