// Auto-generated by OZON category sync
// This file will be automatically updated when you sync categories

export interface CategoryOption {
  value: number;
  label: string;
  isLeaf: boolean;
  disabled: boolean;
  children?: CategoryOption[];
}

export const categoryTree: CategoryOption[] = [];
