"""
OZON插件错误码定义
"""


class OzonErrorCodes:
    """Ozon 插件错误码"""
    BAD_REQUEST = "OZON_BAD_REQUEST"
    FORBIDDEN = "OZON_FORBIDDEN"
    SYNC_CONFLICT = "OZON_SYNC_CONFLICT"
    NOT_FOUND = "OZON_NOT_FOUND"
    RATE_LIMITED = "OZON_RATE_LIMITED"
    UPSTREAM_ERROR = "OZON_UPSTREAM_5XX"
    GUARD_PRICE_VIOLATION = "OZON_GUARD_PRICE_VIOLATION"
    GUARD_STOCK_THRESHOLD = "OZON_GUARD_STOCK_THRESHOLD"